import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useAuth } from '../contexts/auth'

const NavLink = ({ children, to }) => (
  <Link
    href={to}
    className="whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900"
    activeClassName="text-gray-900"
  >
    {children}
  </Link>
)

export default function Layout({ children, ...props }) {
  const { isLoggedIn } = useAuth()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="b-white p-4 shadow-sm">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row justify-between items-center">
          <NavLink to="/">Logo</NavLink>
          <nav className="flex flex-col sm:flex-row sm:space-x-10">
            {isLoggedIn ? (
              <NavLink to="/dashboard">Dashboard</NavLink>
            ) : (
              <NavLink to="/login">Login</NavLink>
            )}
          </nav>
        </div>
      </header>
      <main {...props}>{children}</main>
    </>
  )
}
